[package]
name = "todo_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
lazy_static = "1.5.0"
tera = "1"
todo_rust_openapi = { path = "/home/abishtu/.local/share/repositories/rust/todo_rust_openapi" }
